name: Notify Server

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Notify Server
        env:
          SERVER_URL: ${{ secrets.SERVER_URL }}
        run: |
          curl -X POST "$SERVER_URL" \
              -H "Content-Type: application/json" \
              --data-raw '{
                "repository": "${{ github.repository }}",
                "ref": "${{ github.ref }}",
                "commit": "${{ github.sha }}",
                "previous_commit": "${{ github.event.before }}",
                "pusher": "${{ github.actor }}"
              }'

